Update scenario-c-no-init.yaml

diff --git a/scenario/scenario-c-no-init.yaml b/scenario/scenario-c-no-init.yaml
--- a/scenario/scenario-c-no-init.yaml
+++ b/scenario/scenario-c-no-init.yaml
@@ -32,7 +32,11 @@ spec:
       image: busybox
       command: ["sh", "-c"]
       args:
-        - echo "[fail-container] Simulating failure..." && exit 1
+        - |
+          echo "[fail-container] Simulating repeated failure...";
+          while true; do
+            exit 1
+          done
 
   volumes:
     - name: nginx-conf
